variable "region" {}
variable "availability_zone" {}
variable "ami" {}
variable "instance_type" {}
variable "bucket_name" {}
variable "database_name" {}
variable "database_user" {}
variable "database_pass" {}
variable "admin_user" {}
variable "admin_pass" {}
variable "key_name" {}
variable "pubkey_path" {}
